### ISSUE TITLE
TypeError: Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by tavurth** [Justinidlerz/html-webpack-prefix-plugin#5]
Looks like this plugin is incompatible with webpack 4.

```
    "webpack": "^4.28.3",
    ...
    "html-webpack-plugin": "^4.0.0-beta.5",
    "html-webpack-prefix-plugin": "^1.1.0",
```

```bash
$ webpack --mode production --progress --config webpack.config.client.js
/projects/my-project/node_modules/html-webpack-prefix-plugin/index.js:13
        ? compilation.hooks.htmlWebpackPluginAfterHtmlProcessing.tapAsync.bind(compilation.hooks.htmlWebpackPluginAfterHtmlProcessing, 'html-webpack-plugin-after-html-processing')
                                                                 ^

TypeError: Cannot read property 'tapAsync' of undefined
    at /projects/my-project/node_modules/html-webpack-prefix-plugin/index.js:13:66
    at SyncHook.eval [as call] (eval at create (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:11:1)
    at SyncHook.lazyCompileHook (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/projects/my-project/node_modules/webpack/lib/Compiler.js:581:26)
    at hooks.beforeCompile.callAsync.err (/projects/my-project/node_modules/webpack/lib/Compiler.js:617:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/projects/my-project/node_modules/webpack/lib/Compiler.js:612:28)
    at readRecords.err (/projects/my-project/node_modules/webpack/lib/Compiler.js:284:11)
    at Compiler.readRecords (/projects/my-project/node_modules/webpack/lib/Compiler.js:479:11)
    at hooks.run.callAsync.err (/projects/my-project/node_modules/webpack/lib/Compiler.js:281:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.beforeRun.callAsync.err (/projects/my-project/node_modules/webpack/lib/Compiler.js:278:19)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/projects/my-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.run (/projects/my-project/node_modules/webpack/lib/Compiler.js:275:24)
    at processOptions (/projects/my-project/node_modules/webpack-cli/bin/cli.js:493:14)
    at yargs.parse (/projects/my-project/node_modules/webpack-cli/bin/cli.js:498:3)
    at Object.parse (/projects/my-project/node_modules/yargs/yargs.js:567:18)
    at /projects/my-project/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (/projects/my-project/node_modules/webpack-cli/bin/cli.js:500:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/projects/my-project/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Justinidlerz** [comment]
Yes,  this plugin is write with webpack v1.x, and compatible v2.x after. And i'm sorry about is no update. Could you create a pr for update compatible to v4.x

**Comment by tavurth** [comment]
https://github.com/Justinidlerz/html-webpack-prefix-plugin/pull/6
